<?php
/**
 * Created by PhpStorm.
 * User: zhan
 * Date: 2016/11/19
 * Time: 下午11:04
 */
namespace app\controllers;
use yii;
use app\models\User;
use yii\web\Controller;

class InfoController extends Controller{
public function behaviors()
{
    return parent::behaviors(); // TODO: Change the autogenerated stub
}
    public function actions()
    {
        return [
            'crop'=>[
                'class' => 'hyii2\avatar\CropAction',
                'config'=>[
                    'bigImageWidth' => '200',     //大图默认宽度
                    'bigImageHeight' => '200',    //大图默认高度
                    'middleImageWidth'=> '100',   //中图默认宽度
                    'middleImageHeight'=> '100',  //中图图默认高度
                    'smallImageWidth' => '50',    //小图默认宽度
                    'smallImageHeight' => '50',   //小图默认高度

                    //头像上传目录（注：目录前不能加"/"）
                    'uploadPath' => 'uploads/avatar/',
                ]
            ]
        ];

    }
public function actionIndex(){
    $user = User::find()->where(['id'=>Yii::$app->user->identity->id])->one();
    return $this->render('index',['user'=>$user]);
}
public function actionLook($id){
    $user = User::find()->where(['id'=>$id])->one();
    return $this->render('index',['user'=>$user]);
}
 public function actionEdit(){
//        $model = new User();
        $model = User::find()->where(['id'=>$_GET['user_id']])->one();
        if($model->load(Yii::$app->request->post())){
		if($model->newpass !=null){
            $saltpass = md5(time());
            $model->saltpass = $saltpass;
            $model->password = md5($model->newpass.$saltpass);
            $model->newpass = $model->repass = '';
		}
		if($model->save()){
                return $this->redirect(['/info/index']);
            }
            else{
                echo json_encode($model->getErrors());
            }
        }
    }
}
