<?php
/**
 * Created by PhpStorm.
 * User: zhan
 * Date: 2017/4/20
 * Time: 下午9:28
 */
namespace app\models;
use yii\base\Model;
use yii\web\UploadedFile;

class Upload extends Model{
    public $file;
    public function rules()
    {
   //     return parent::rules(); // TODO: Change the autogenerated stub
        return [
          [['file'],'file']
        ];
    }
}